### ISSUE TITLE
Probleme mit Umlauten

### ISSUE THREAD

**Issue by renmet** [braindead1/HomeHub-WebUI#2]
Hallo,

anscheinend findet Homehub keine Komponenten mit Umlauten. Egal was man in der custom.json eintragt, sobald eine dieser Komponenten eingetragen ist wird in Homehub nichts mehr angezeigt (auch in allen anderen Kategorien). Unter dem Punkt "Heizung" wird der Heizkörper aber richtig angezeigt.

Export.json:

{"component":"HM-CC-RT-DN","parent_device_type":"HM-CC-RT-DN","parent_device_interface":"BidCos-RF","name":"Heizk\u00f6rper Bad 4","type":"17","address":"LEQ08xxxxx:4","ise_id":"2437","direction":"SENDER","parent_device":"2404","index":"4","group_partner":"","aes_available":"false","transmission_mode":"DEFAULT","visible":"true","ready_config":"true","operate":"true","datapoints":[{"name":"BidCos-RF.LEQ08xxxxx:4.CONTROL_MODE","type":"CONTROL_MODE","ise_id":"2444","state":"1","value":"1","valuetype":"16","valueunit":"","timestamp":"1457585423","operations":"5"},{"name":"BidCos-RF.LEQ08xxxxx:4.FAULT_REPORTING","type":"FAULT_REPORTING","ise_id":"2445","state":"0","value":"0","valuetype":"16","valueunit":"","timestamp":"1457585423","operations":"5"},{"name":"BidCos-RF.LEQ08xxxxx:4.BATTERY_STATE","type":"BATTERY_STATE","ise_id":"2440","state":"3.000000","value":"3.000000","valuetype":"4","valueunit":"V","timestamp":"1457585423","operations":"5"},{"name":"BidCos-RF.LEQ08xxxxx:4.VALVE_STATE","type":"VALVE_STATE","ise_id":"2480","state":"0","value":"0","valuetype":"16","valueunit":"%","timestamp":"1457585423","operations":"5"},{"name":"BidCos-RF.LEQ08xxxxx:4.BOOST_STATE","type":"BOOST_STATE","ise_id":"2442","state":"0","value":"0","valuetype":"16","valueunit":"min","timestamp":"1457585423","operations":"5"},{"name":"BidCos-RF.LEQ08xxxxx:4.ACTUAL_TEMPERATURE","type":"ACTUAL_TEMPERATURE","ise_id":"2438","state":"21.300000","value":"21.300000","valuetype":"4","valueunit":"\u00b0C","timestamp":"1457585423","operations":"5"},{"name":"BidCos-RF.LEQ08xxxxx:4.SET_TEMPERATURE","type":"SET_TEMPERATURE","ise_id":"2479","state":"4.500000","value":"4.500000","valuetype":"4","valueunit":"\u00b0C","timestamp":"1457585423","operations":"7"},{"name":"BidCos-RF.LEQ08xxxxx:4.AUTO_MODE","type":"AUTO_MODE","ise_id":"2439","state":"false","value":"","valuetype":"2","valueunit":"","timestamp":"0","operations":"2"},{"name":"BidCos-RF.LEQ08xxxxx:4.MANU_MODE","type":"MANU_MODE","ise_id":"2468","state":"0.000000","value":"","valuetype":"4","valueunit":"\u00b0C","timestamp":"0","operations":"2"},{"name":"BidCos-RF.LEQ08xxxxx:4.BOOST_MODE","type":"BOOST_MODE","ise_id":"2441","state":"false","value":"","valuetype":"2","valueunit":"","timestamp":"0","operations":"2"},{"name":"BidCos-RF.LEQ08xxxxx:4.COMFORT_MODE","type":"COMFORT_MODE","ise_id":"2443","state":"false","value":"","valuetype":"2","valueunit":"","timestamp":"0","operations":"2"},{"name":"BidCos-RF.LEQ08xxxxx:4.LOWERING_MODE","type":"LOWERING_MODE","ise_id":"2467","state":"false","value":"","valuetype":"2","valueunit":"","timestamp":"0","operations":"2"},{"name":"BidCos-RF.LEQ08xxxxx:4.PARTY_MODE_SUBMIT","type":"PARTY_MODE_SUBMIT","ise_id":"2469","state":"","value":"","valuetype":"20","valueunit":"","timestamp":"0","operations":"2"},{"name":"BidCos-RF.LEQ08xxxxx:4.PARTY_TEMPERATURE","type":"PARTY_TEMPERATURE","ise_id":"2478","state":"5.000000","value":"5.000000","valuetype":"4","valueunit":"\u00b0C","timestamp":"1457585423","operations":"3"},{"name":"BidCos-RF.LEQ08xxxxx:4.PARTY_START_TIME","type":"PARTY_START_TIME","ise_id":"2472","state":"0","value":"0","valuetype":"16","valueunit":"minutes","timestamp":"1457585423","operations":"3"},{"name":"BidCos-RF.LEQ08xxxxx:4.PARTY_START_DAY","type":"PARTY_START_DAY","ise_id":"2470","state":"1","value":"1","valuetype":"16","valueunit":"day","timestamp":"1457585423","operations":"3"},{"name":"BidCos-RF.LEQ08xxxxx:4.PARTY_START_MONTH","type":"PARTY_START_MONTH","ise_id":"2471","state":"1","value":"1","valuetype":"16","valueunit":"month","timestamp":"1457585423","operations":"3"},{"name":"BidCos-RF.LEQ08xxxxx:4.PARTY_START_YEAR","type":"PARTY_START_YEAR","ise_id":"2473","state":"0","value":"0","valuetype":"16","valueunit":"year","timestamp":"1457585423","operations":"3"},{"name":"BidCos-RF.LEQ08xxxxx:4.PARTY_STOP_TIME","type":"PARTY_STOP_TIME","ise_id":"2476","state":"0","value":"0","valuetype":"16","valueunit":"minutes","timestamp":"1457585423","operations":"3"},{"name":"BidCos-RF.LEQ08xxxxx:4.PARTY_STOP_DAY","type":"PARTY_STOP_DAY","ise_id":"2474","state":"1","value":"1","valuetype":"16","valueunit":"day","timestamp":"1457585423","operations":"3"},{"name":"BidCos-RF.LEQ08xxxxx:4.PARTY_STOP_MONTH","type":"PARTY_STOP_MONTH","ise_id":"2475","state":"1","value":"1","valuetype":"16","valueunit":"month","timestamp":"1457585423","operations":"3"},{"name":"BidCos-RF.LEQ08xxxxx:4.PARTY_STOP_YEAR","type":"PARTY_STOP_YEAR","ise_id":"2477","state":"0","value":"0","valuetype":"16","valueunit":"year","timestamp":"1457585423","operations":"3"}]},

Export.txt:

HM-CC-RT-DN|Heizkörper Bad 4|BidCos-RF|LEQ08xxxxx|4|VISIBLE=true|OPERATE=true|CONTROL_MODE=2444|FAULT_REPORTING=2445|BATTERY_STATE=2440|VALVE_STATE=2480|BOOST_STATE=2442|ACTUAL_TEMPERATURE=2438|SET_TEMPERATURE=2479|AUTO_MODE=2439|MANU_MODE=2468|BOOST_MODE=2441|COMFORT_MODE=2443|LOWERING_MODE=2467|PARTY_MODE_SUBMIT=2469|PARTY_TEMPERATURE=2478|PARTY_START_TIME=2472|PARTY_START_DAY=2470|PARTY_START_MONTH=2471|PARTY_START_YEAR=2473|PARTY_STOP_TIME=2476|PARTY_STOP_DAY=2474|PARTY_STOP_MONTH=2475|PARTY_STOP_YEAR=2477|

LG

**Comment by braindead1** [comment]
Ich habe auch einen "Bad Heizkörper" und bei mir gibt es keine Probleme mit den Umlauten. Ich tippe darauf, dass Du ein Problem mit der Dateikodierung hast. Kannst Du bitte überprüfen, ob Deine Dateien utf-8 kodiert sind?

**Comment by renmet** [comment]
Hallo,

bei einem IIS 8? Läuft auf Windows Server 2012 R2

LG

**Comment by all-solutions** [comment]
Hallo renmet,

ja, die custom.json muss in **UTF-8 Codierung** abgespeichert werden. Viele Editoren auf Windows-Maschinen nehmen da gerne CP1252 (Windows) und dann geht das in die Hose mit den Umlauten.

Gruß
Manu

**Comment by renmet** [comment]
Hallo,

die Datei war als UTF-8 ohne BOM kodiert. Ich habe sie jetzt als reine UTF-8 kodiert aber das hat leider auch nichts geändert. Ich schiebe das ganze jetzt mal auf einen Linux Webserver und melde mich danach nochmals.

Auch auf einer Linux Umgebung bringt es keine Besserung. Interessant ist aber, das andere Geräte mit Umlauten funktionieren und ich keinen Unterschied in der JSON sehe:

Heizkörper (damit bleibt alles leer):

```
  {
    "name": "Heizkörper Bad 4",
    "icon": "sani_heating.png",
    "display_name": "Heizkörper"
  }
```

Türöffner (damit funktioniert alles wie es soll):

```
  {
    "name": "OLED FB Türöffner Eingangstür",
    "icon": "it_remote.png",
    "display_name": "Türöffner Eingangstür",
    "append_divider": "true"
  },
```

Der einzige Unterschied ist "append_divider" aber das macht ja nur einen Abstand und sonst nichts.

UPDATE: Ich habe jetzt nochmals von vorne begonnen und jetzt wird auch der Heizkörper angezeigt. Leider fehlt mir halt das WARUM :(

LG
René
